"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['decomposePng.py']
APP_NAME = "合图分解"
DATA_FILES = []
OPTIONS = {
	'iconfile':'icon.icns',
	'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "利用JSON配置将PNG合图分解成单个图片。",
        'CFBundleIdentifier': "com.sch.osx.decomposepng",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2019, Stone Hui, All Rights Reserved"
    },
    'packages': ['PIL'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
